# Generated by Django 3.0 on 2019-12-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=12)),
            ],
        ),
    ]
